### ISSUE TITLE
Missing registration response validation?

### ISSUE THREAD

**Issue by BarakSilverfort** [wallix/webauthn#29]
Hello, I've looked into your code, and while looking at the flow, I've seen that you do not validate the registration response.
Am I missing something? or was it left out for any reason?

https://www.w3.org/TR/webauthn/#registering-a-new-credential

**Comment by Awides** [comment]
@BarakSilverfort Why did you close this?

**Comment by BarakSilverfort** [comment]
@coreymt I dove deeper into the code and found validation for most of the steps.
